# Makefile

# Command to run in development mode
dev:
	ENV=development cargo run

# Command to run in production mode
prod:
	ENV=production cargo run

# Command to test (just an example)
test:
	cargo test
