apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agentex-builds-role
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "watch", "list"]