apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agentex-builds-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: agentex
  namespace: default
- kind: ServiceAccount
  name: agentex-workers
  namespace: default
roleRef:
  kind: Role
  name: agentex-builds-role
  apiGroup: rbac.authorization.k8s.io
