apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: agentex-builds-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "watch", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "watch", "list"]