apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agentex-role-binding
  namespace: agentex-agents
subjects:
- kind: ServiceAccount
  name: agentex-workers
  namespace: default
roleRef:
  kind: Role
  name: agentex-role
  apiGroup: rbac.authorization.k8s.io
