# helmfile.dev.yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: temporal
    url: https://go.temporal.io/helm-charts
  - name: harbor
    url: https://helm.goharbor.io

releases:
#  - name: redis
#    chart: bitnami/redis
#
#  - name: kafka
#    chart: bitnami/kafka
#    namespace: kafka
#    values:
#      - zookeeper:
#          replicaCount: 1
#        replicaCount: 1
#        persistence:
#          enabled: true
#          size: 10Gi

  - name: temporal
    chart: temporal/temporal
    values:
      - server:
          replicaCount: 1
        cassandra:
          config:
            cluster_size: 1
        elasticsearch:
          replicas: 1
        prometheus:
          enabled: false
        grafana:
          enabled: false

  - name: harbor
    chart: harbor/harbor
    namespace: harbor
    values:
      - expose:
          type: clusterIP
          tls:
            enabled: false
        externalURL: "http://harbor.harbor.svc.cluster.local:80"
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              size: 10Gi

  - name: agentex-workers
    chart: ./agentex-workers
    values:
      - ./agentex-workers/values.yaml

  - name: agentex
    chart: ./agentex
    values:
      - ./agentex/values.yaml
