# helmfile.dev.yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: temporal
    url: https://go.temporal.io/helm-charts

releases:
  - name: redis
    chart: bitnami/redis
    values:
      - auth:
          enabled: false

  - name: temporal
    chart: temporal/temporal
    namespace: temporal
    values:
      - server:
          replicaCount: 1
        cassandra:
          config:
            cluster_size: 1
        elasticsearch:
          replicas: 1
        prometheus:
          enabled: false
        grafana:
          enabled: false

  - name: agentex-workers
    chart: ./agentex-workers
    values:
      - ./agentex-workers/values.yaml

  - name: agentex
    chart: ./agentex
    values:
      - ./agentex/values.yaml
