"""init_action

Revision ID: 445f4881318d
Revises: 92f9143a4bd9
Create Date: 2024-10-02 16:09:26.141363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '445f4881318d'
down_revision: Union[str, None] = '92f9143a4bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('packaging_method', sa.Enum('DOCKER', name='packagingmethod'), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('docker_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_version')
    )
    op.create_index(op.f('ix_actions_name'), 'actions', ['name'], unique=False)
    op.create_index(op.f('ix_actions_version'), 'actions', ['version'], unique=False)
    op.create_table('agent_action',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'action_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_action')
    op.drop_index(op.f('ix_actions_version'), table_name='actions')
    op.drop_index(op.f('ix_actions_name'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
