"""add_build_info_to_actions

Revision ID: ba670c9fa1c8
Revises: c8b1f183c866
Create Date: 2024-10-06 18:40:42.815388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba670c9fa1c8'
down_revision: Union[str, None] = 'c8b1f183c866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('build_job_name', sa.String(), nullable=True))
    op.add_column('actions', sa.Column('build_job_namespace', sa.String(), nullable=True))
    op.add_column('actions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('actions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_actions_build_job_name'), 'actions', ['build_job_name'], unique=False)
    op.add_column('agents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('agents', 'updated_at')
    op.drop_column('agents', 'created_at')
    op.drop_index(op.f('ix_actions_build_job_name'), table_name='actions')
    op.drop_column('actions', 'updated_at')
    op.drop_column('actions', 'created_at')
    op.drop_column('actions', 'build_job_namespace')
    op.drop_column('actions', 'build_job_name')
    # ### end Alembic commands ###
